### ISSUE TITLE
CuSparseError: CUSPARSE_STATUS_ALLOC_FAILED 

### ISSUE THREAD

**Issue by JBreunig** [clara-parabricks/rapids-single-cell-examples#11]
Getting the error: 
---------------------------------------------------------------------------

> CuSparseError                             Traceback (most recent call last)
> <timed exec> in <module>
> 
> ~/anaconda3/envs/rapidgenomics/lib/python3.7/site-packages/cupyx/scipy/sparse/csr.py in tocsc(self, copy)
>     254         """
>     255         # copy is ignored
> --> 256         return cusparse.csr2csc(self)
>     257 
>     258     def tocsr(self, copy=False):
> 
> ~/anaconda3/envs/rapidgenomics/lib/python3.7/site-packages/cupy/cusparse.py in csr2csc(x)
>     648         data.data.ptr, indices.data.ptr, indptr.data.ptr,
>     649         cusparse.CUSPARSE_ACTION_NUMERIC,
> --> 650         cusparse.CUSPARSE_INDEX_BASE_ZERO)
>     651     return cupyx.scipy.sparse.csc_matrix(
>     652         (data, indices, indptr), shape=x.shape)
> 
> ~/anaconda3/envs/rapidgenomics/lib/python3.7/site-packages/cupy/cusparse.py in _call_cusparse(name, dtype, *args)
>      61         raise TypeError
>      62     f = getattr(cusparse, prefix + name)
> ---> 63     return f(*args)
>      64 
>      65 
> 
> cupy/cuda/cusparse.pyx in cupy.cuda.cusparse.scsr2csc()
> 
> cupy/cuda/cusparse.pyx in cupy.cuda.cusparse.scsr2csc()
> 
> cupy/cuda/cusparse.pyx in cupy.cuda.cusparse.check_status()
> 
> CuSparseError: CUSPARSE_STATUS_ALLOC_FAILED

after the block:
%%time
tmp_norm = normalized.tocsc()
ACE2_raw = tmp_norm[:, genes[genes == "ACE2"].index[0]].todense().ravel()
TMPRSS2_raw = tmp_norm[:, genes[genes == "TMPRSS2"].index[0]].todense().ravel()
EPCAM_raw = tmp_norm[:, genes[genes == "EPCAM"].index[0]].todense().ravel()

del tmp_norm

This is using all of the code in the Jupyter notebook.  (Got the same error in Spyder and Jupyter notebook.)

A few quick questions that may relate to this:
1) the max I can set the POOL_SIZE_GB is 6.  (1080 Ti).  Can you explain a bit more how to set this appropriately?
2) Is there a reason this code is present twice within 4 blocks of code?

> input_file = "krasnow_hlca_10x_UMIs.sparse.h5ad" (i changed to my local path).

Thanks in advance!

**Comment by cjnolet** [comment]
@JBreunig, 

I just made some changes to the notebook. You should no longer have to set the pool allocator and the extra file path variable has been removed.

Can you pull down the changes and give it another try? I executed the notebook end to end with the changes and the device memory looks to peak around 3.5GB

**Comment by JBreunig** [comment]
Everything works now...insanely fast!
